plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.2.cjs

nodeLinker: pnp
preferTruncatedLines: true
enableScripts: true
enableNetwork: true
initScope: yarnpkg
enableTelemetry: false
enableMessageNames: false
