name: Integration/Delivery
on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened

jobs:
  check_build_working:
    name: "Build and Typecheck"
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        action:
          - build
          - typecheck
    steps:
      - uses: actions/checkout@v2.1.0

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - run: pnpm next-tel-disable

      - name: Build Project
        run: pnpm ${{ matrix.action }}
  static_analysis:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2.1.0

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - run: pnpm next-tel-disable

      - run: pnpm lint

  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0
        with:
          record: false
          install: false
          component: true

  build_and_deploy:
    runs-on: ubuntu-latest
    needs:
      - test
      - static_analysis
    if: ${{ github.event_name == 'pull_request' }}
    environment:
      name: Staging
      url: ${{steps.deploy_staging.outputs.preview-url}}
    steps:
      - uses: actions/checkout@v2.1.0

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - run: pnpm next-tel-disable

      - run: pnpm build

      - uses: amondnet/vercel-action@v20 #deploy
        id: deploy_staging
        with:
          vercel-token: ${{ secrets.VERCEL_SECRET }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          working-directory: out
