name: Integration/Delivery
on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened

jobs:
  check_build_working:
    name: Transpile Code
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Disable Telemetry
        run: pnpm next-tel-disable

      - name: Build Project
        run: pnpm build

  Checking_code_and_deploy_preview:
    name: Pull Request Guard
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.1.0

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Disable telemetry
        run: pnpm next-tel-disable

      - name: Static code analysis
        run: pnpm lint

      - name: Transpile Code
        run: pnpm build

      - name: Component Test
        uses: cypress-io/github-action@v4.1.0
        with:
          record: false
          install: false
          component: true

      - uses: amondnet/vercel-action@v20 #deploy
        name: Deploy Staging
        with:
          vercel-token: ${{ secrets.VERCEL_SECRET }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          working-directory: out
